export enum Pagination {
  Login = "LoginPage",
  RoleSelector = "RoleSelectorPage",
  SignUp = "SignUpPage",
  Profile = "ProfilePage",
  EditProfile = "EditProfilePage",
  SupplyChainInvite = "SupplyChainInvitePage",
  SupplyChainInvitesList = "SupplyChainInvitesListPage",
  SupplyChainList = "SupplyChainListPage",
  SupplyChainViewer = "SupplyChainViewerPage",
  UserFilter = "UserFilterPage",
  SupplyChainCreate = "SupplyChainCreatePage",
  SupplyChainSuggestion = "SupplyChainSuggestionPage",
  AssetCreate = "AssetCreatePage",
}
